CREATE TABLE users (
    id INT PRIMARY KEY,
    username VARCHAR(30) UNIQUE NOT NULL,
    email VARCHAR(30) NOT NULL,
    password VARCHAR(100) NOT NULL
);

TRUNCATE TABLE users;


ALTER TABLE users
ALTER COLUMN id TYPE VARCHAR(30);

ALTER TABLE users
ALTER COLUMN name TYPE VARCHAR(30);

ALTER TABLE users
ALTER COLUMN email TYPE VARCHAR(30);

ALTER TABLE users
ALTER COLUMN password TYPE VARCHAR(100);